### ISSUE TITLE
VOIP Migration

### ISSUE THREAD

**Issue by jhoblitt** [socallinuxexpo/SCALE-Planning#204]
Migrate away from self hosted asterisk instance on `scale-voip.actusa.net`.  Options need to be evaluated including using the current upstream sip trunk providers hosted pbx service.

**Comment by irabinovitch** [comment]
Our SIP provider at the moment is Teliax it terminates at scale-voip.actusa.net, which runs asterisk.
That system in turn offers an IVR and voice mail services for SCALE team members who request it.  Calls are either forwarded to their cel phones or to a SIP device if it is connected.

There is presently only 1 user (Doug Widman) who occasionally uses the SIP semi-actively. Everyone else just lets calls go to local voicemail or forward to their cel.

Teliax now offers a hosted PBX service.  If we do not need SIP/IAX devices it looks like we'll only pay for the line and inbound/outgoing calls used in the forwarding service.  

Pros:
- Easy to setup
- No on going monitoring / management.
- Low Cost

Cons:
- If we do need hard phones via SIP or IAX they cost about $25~/device/month
- All existing extensions at SCALE are 3 digits. Teliax only supports 2 and 4 digit extensions. Existing documentation will need to be updated. (eg business cards, websites, etc)

**Comment by irabinovitch** [comment]
I've reached out to most of the folks with extensions and they dont see to actively be using them. So the main purpose of voip at this point is to offer a customer service number to tie to our merchant account,  and the sponsorship calls I get year round. 

With that in mind, Id probably be the only person impacted by the extension change.

I'll leave it till the end of the week for objections, and otherwise sign us up for Teliax Ivy and start the process of moving our toll free number there. 

Any volunteers for recreating our IVR menu on Ivy?  Probably worth re-recording our message prompts as well.

**Comment by efbatey** [comment]
Seems trivial to run Trix on a local machine.. been doing so 4 to 5 years.  Trunk is $3/month Voipstreet

**Comment by efbatey** [comment]
It made a pretty handy re-routable help desk number for the shows ..

**Comment by irabinovitch** [comment]
I dont believe we're looking to revive the help desk at this point, but we do no need a phone number for sponsors and for a customer service line for our merchant accounts used for registration.  We've setup a new PBX on Teliax IVY.  The main drawback here is that we had to change everyone's extensions.

Right now it's using my voice since nobody else volunteered to be the voice of the menu.  I've asked Teliax to cutover as soon as they can.

**Comment by irabinovitch** [comment]
Confirmed numbers were rerouted

**Comment by efbatey** [comment]
I was #213, I believe.  Don't know if I remain relevant.  If I have an
extension, pls, advise.  R / Everett

On Tue, Jun 28, 2016 at 9:00 AM, Ilan Rabinovitch <notifications@github.com>
wrote:

> Closed #204 <https://github.com/socallinuxexpo/SCALE-Planning/issues/204>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/socallinuxexpo/SCALE-Planning/issues/204#event-706557841>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AR1lTveZq5KdXlGZXVe5YB5LDm1IKQBWks5qQUUGgaJpZM4IYlUK>
> .
>



-- 
 R/  Everett Batey / Skype: wa6cre-10 / efbatey@gmail.com
  or efbarc@cotdazr.org or wa6cre@rabbitradio.org or lioneverett@gmail.com
   Auxiliary Lions 4-A3 Web  Lions 4-A3 Calendar  /
http://lions.vhwy.com/lcal
    (805) 616-2471 / G-Talk/Twitter: efbatey / CrisisLinks
http://bit.ly/cw95Um
      Please visit So Calif Linux Expo http://www.socallinuxexpo.org

**Comment by irabinovitch** [comment]
@efbatey Thanks. You are correct. You did offer up trixbox. At this point, you dont have an extension, but if you'd like one please let us know where you'd like your calls forwarded.

**Comment by efbatey** [comment]
Trying to recover my Google (G Suite) ev@socallinuxexpo.org password ..
I'm getting:
    Couldn't sign you in
    ev@socallinuxexpo.org
    Contact your domain admin for help.

Found a link which has expired.  Need help

Also,  who is the list manager?  Not sure what lists I am on for
scale?  Think I am on Planning.

 VR/  Everett Batey / efbatey@gmail.com / Skype: wa6cre-10 +1-703-879-6471
   Auxiliary Lions 4-A3 Web  Lions 4-A3 Calendar  / http://lions.vhwy.com/lcal
    +1-805-616-2471 // Please visit So Calif Linux Expo
http://www.socallinuxexpo.org
