### ISSUE TITLE
migrate discussion lists

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#213]
Migrate the mailman services running on lists.linuxfests.org from ActUSA to another provider as per #194 .  If we stick with mailman it must be version 2.1.20+ to support #193. The current release as of April is 2.1.22.

**Comment by irabinovitch** [comment]
@jhoblitt @jaymzh Started on some recipes for this, but Centos7 only includes Mailman 2.1.15 which is fairly old and doesn't include user-friendly DMARC handling.  

Do we want to grab the source install? Build our own packages? other options/ideas?

**Comment by jhoblitt** [comment]
Wow, the mailman package is part of `base`, which is why it isn't being updated. I haven't run a mailman install since before 2010 and the start of the python3 conversion.   Typically, if I need a newer version of an existing base or epel7 package, I will first check copr and then fall back to attempting to modify the `.spec` in the official srpm.

I checked copr for mailman and didn't see anything that looked promising.  I believe this is the latest src.rpm: http://vault.centos.org/7.2.1511/os/Source/SPackages/mailman-2.1.15-21.el7_1.src.rpm  I will take a quick look at updating the package.

**Comment by jhoblitt** [comment]
The fedpkg version is 2.1.21.  There are often rpm macro changes before current fedora and el7 but some times it is easier to backport than updating an older spec file.

**Comment by jhoblitt** [comment]
**Completely untested**

fedora rawhide package built for epel7.

https://www.dropbox.com/s/pwczzx8mcudftbn/mailman-2.1.21-1.el7.centos.x86_64.rpm?dl=0

**Comment by irabinovitch** [comment]
@jhoblitt checkout the mailman branch on scale-chef.  The rawhide package seemed to work on Centos7 without rebuilding, but happy to use yours if we think thats a better option.

**Comment by irabinovitch** [comment]
I believe this is now complete.
